version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=282865065290.dkr.ecr.us-east-1.amazonaws.com/ddd
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${282865065290.dkr.ecr.us-east-1.amazonaws.com/ddd}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=lastest}
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest
      - docker tag ${REPOSITORY_URI}:latest $REPOSITORY_URI:IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - 'Dockerrun.aws.json'
