version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cursosdev
      MYSQL_USER: cursosdev
      MYSQL_PASSWORD: 12345
    ports:
      - 3307:3306
    volumes:
      - vol-mysql:/var/lib/mysql

volumes:
  vol-mysql:
