version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
